import fs from "node:fs/promises";
import path from "node:path";

import { CodeBuddyRunner } from "../../core/eval/runners.mjs";
import { ensureDir } from "../../core/fs.mjs";
import { defineAgentAdapter, activePatchesForAdapter } from "../sdk.mjs";
import { replayCodeBuddyProtocol } from "../protocol.mjs";

const adapter = defineAgentAdapter({
  id: "codebuddy",
  displayName: "CodeBuddy Code",
  aliases: ["codebuddy", "codebuddy-code", "cbc"],
  binaries: ["codebuddy", "cbc"],
  maturity: "beta",
  capabilities: ["evaluate", "compile", "replay"],
  protocol: "behavectl.codebuddy-stream-json.v1",
  surfaces: [".codebuddy/rules/behavectl/"],
  replayProtocol(input) {
    return replayCodeBuddyProtocol(input);
  },
  createRunner(options = {}) {
    return new CodeBuddyRunner(options);
  },
  async compile({ repoRoot, patches }) {
    const selected = activePatchesForAdapter(patches, adapter);
    const dir = path.join(repoRoot, ".codebuddy", "rules", "behavectl");
    const expected = new Set();

    if (selected.length) await ensureDir(dir);

    for (const patch of selected) {
      const file = path.join(dir, `${patch.id}.md`);
      expected.add(path.basename(file));
      const body = [
        "---",
        `description: Behavectl managed behavior ${patch.id}`,
        "alwaysApply: true",
        "enabled: true",
        "---",
        "",
        "<!-- Generated by Behavectl. Do not edit directly. -->",
        `<!-- patch: ${patch.id} -->`,
        "",
        "# Managed behavior",
        "",
        `- ${patch.behavior.statement}`,
        "",
      ].join("\n");
      await fs.writeFile(file, body, "utf8");
    }

    try {
      const files = await fs.readdir(dir, { withFileTypes: true });
      for (const entry of files) {
        if (entry.isFile() && entry.name.endsWith(".md") && !expected.has(entry.name)) {
          const file = path.join(dir, entry.name);
          const body = await fs.readFile(file, "utf8");
          const id = path.basename(entry.name, ".md");
          if (
            body.includes("<!-- Generated by Behavectl. Do not edit directly. -->") &&
            body.includes(`<!-- patch: ${id} -->`)
          ) {
            await fs.rm(file, { force: true });
          }
        }
      }
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }

    if (selected.length === 0) {
      try {
        await fs.rmdir(dir);
      } catch (error) {
        if (!["ENOENT", "ENOTEMPTY", "EEXIST"].includes(error?.code)) throw error;
      }
    }

    return {
      adapter: adapter.id,
      path: path.relative(repoRoot, dir),
      count: selected.length,
    };
  },
});

export default adapter;
