import fs from "node:fs/promises";
import path from "node:path";

import { CodexRunner } from "../../core/eval/runners.mjs";
import { defineAgentAdapter, activePatchesForAdapter } from "../sdk.mjs";
import { replayCodexProtocol } from "../protocol.mjs";

const START = "<!-- behavectl:start -->";
const END = "<!-- behavectl:end -->";

const adapter = defineAgentAdapter({
  id: "codex",
  displayName: "Codex",
  aliases: ["codex"],
  binaries: ["codex"],
  maturity: "stable",
  capabilities: ["evaluate", "compile", "replay"],
  protocol: "behavectl.codex-exec-jsonl.v1",
  surfaces: ["AGENTS.md"],
  replayProtocol(input) {
    return replayCodexProtocol(input);
  },
  createRunner(options = {}) {
    return new CodexRunner(options);
  },
  async compile({ repoRoot, patches }) {
    const selected = activePatchesForAdapter(patches, adapter);
    const file = path.join(repoRoot, "AGENTS.md");
    let existing = "";
    let existed = true;

    try {
      existing = await fs.readFile(file, "utf8");
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
      existed = false;
    }

    const start = existing.indexOf(START);
    const end = existing.indexOf(END);

    if (selected.length === 0) {
      if (start >= 0 && end >= start) {
        const after = end + END.length;
        const human = `${existing.slice(0, start)}${existing.slice(after)}`
          .replace(/\n{3,}/g, "\n\n")
          .trim();
        if (human) await fs.writeFile(file, `${human}\n`, "utf8");
        else await fs.rm(file, { force: true });
      }
      return {
        adapter: adapter.id,
        path: "AGENTS.md",
        count: 0,
        removed: existed,
      };
    }

    const rules = selected
      .map((patch) => `- ${patch.behavior.statement}  <!-- ${patch.id} -->`)
      .join("\n");

    const managed = [
      START,
      "<!-- Generated by Behavectl. Do not edit this block directly. -->",
      "",
      "## Behavectl managed behavior",
      "",
      rules,
      END,
    ].join("\n");

    let next;
    if (start >= 0 && end >= start) {
      const after = end + END.length;
      next = existing.slice(0, start) + managed + existing.slice(after);
    } else {
      const prefix = existing.trimEnd();
      next = prefix ? `${prefix}\n\n${managed}\n` : `${managed}\n`;
    }

    await fs.writeFile(file, next, "utf8");
    return { adapter: adapter.id, path: "AGENTS.md", count: selected.length };
  },
});

export default adapter;
